spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.99.100:9092
          zkNodes: 192.168.99.100:2181
      default-binder: kafka
  sleuth:
    integration:
      enabled: false
    scheduled:
      enabled: false
    sampler:
      percentage: 1.0
    stream:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost/wiki_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: choerodon
    password: choerodon
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration: # 数据库下划线转驼峰配置
    mapUnderscoreToCamelCase: true
wiki:
  client: xwiki
  url: http://xwiki-alpha.saas.hand-china.com
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8000/eureka/}
    registryFetchIntervalSeconds: 10
security:
  basic:
    enabled: false

